### ISSUE TITLE
Notifications through org.freedesktop.Notifications

### ISSUE THREAD

**Issue by Tass0sm** [rodlie/powerdwarf#36]
Thank you for making this program. I like it, and I can't find any other programs which nicely fill the role it fills on my desktop.

Instead of using the QT System Tray icon showMessage notifications, should/could it use freedesktop notifications?

I have made a [fork of this project](https://github.com/Tass0sm/powerkit) and added the code to do this there. It's mainly taken from the notification code used in [flameshot](https://github.com/flameshot-org/flameshot/blob/master/src/utils/systemnotification.cpp). I'm not sure if what I've made is too good, but it seems to work. If this is something worth adding to the real project, I could open a pull request.

Please let me know if that is a good idea.

**Comment by rodlie** [comment]
Hi,

This project has stalled a bit, mostly since I moved over to macOS on most of my computers. I should really finish powerkit2, as there are several nice features added there. I had plans to add support for org.freedesktop.notifications, but never came that far.

I can try to get powerkit2 in a better state, but I don't know when I have the time, maybe later this month.

**Comment by snprajwal** [comment]
@rodlie is powerkit still maintained/active? If so, I would like to open a PR to fix this, and a few other issues. I have been using powerkit for quite a while now, and it's pretty awesome :) would love to help out if the project is still alive

**Comment by rodlie** [comment]
> is powerkit still maintained/active?

Kind of ... Been on macOS for a couple of years, so nothing has happened. But I'm now mostly on a PC laptop running Linux, so I might do something in the near future.

I will at least finish what I started in `main`.
